### ISSUE TITLE
[Nhóm #2] Lỗi phi chức năng trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31141020929** [UEHMonQAQC/K40#24]
a. Web Browser: Google Chrome 58.0.3029.96
b. Các bước để phát hiện lỗi:
i. #1: Đăng nhập vào trang  cá nhân trên trang online 
ii. #2: Vào mục Ghi danh nhu cầu học
iii. #3: Chọn mục Số tín chỉ của môn Kỹ Năng Mềm. Click chuột phải Inspect
![image](https://cloud.githubusercontent.com/assets/26455325/25746813/471764b2-31cf-11e7-9e4f-92cf46756e35.png)
iv. #4: Chỉnh sửa được như trong hình
![image](https://cloud.githubusercontent.com/assets/26455325/25746836/5f3bdfd2-31cf-11e7-9fd3-47e762ad7df9.png)

c .Kết quả thực tế: Chỉnh sửa được 
d.Kết quả mong đợi : Không chỉnh sửa được

**Comment by 31131021217** [comment]
Các bạn sửa lại tiêu đề nhóm thành #2 cho đồng nhất nhé. Mình đã thử nhưng không thấy xuất hiện lỗi như mô tả, các bạn kiểm tra lại giúp mình.

**Comment by 31141020929** [comment]
đã fix

**Comment by 31131021217** [comment]
Xin lỗi nhóm nhưng mình refresh trang thì thông tin vẫn trở về như cũ nên đây không phải lỗi. Các bạn tìm lỗi khác nha.
Cảm ơn các bạn.
