### ISSUE TITLE
[Nhóm 4] Lỗi chức năng (Lỗi 404 Not Found) trên trang http://jbis.ueh.edu.vn

### ISSUE THREAD

**Issue by 31141021379** [UEHMonQAQC/K40#28]
a. Web browser: Google Chrome version 58.0.3029.81
b. Các bước phát hiện lỗi:
    i. #1. Truy cập trang http://jbis.ueh.edu.vn
    ii. #2. Bấm vào nút "Đăng kí" như hình
![image](https://cloud.githubusercontent.com/assets/26585215/25467646/d26cb5f4-2b39-11e7-9810-b5375f62f417.png)
c. Kết quả thực tế: Lỗi 404 Not Found
![image](https://cloud.githubusercontent.com/assets/26585215/25467655/f24db63e-2b39-11e7-93e0-921bd1dd7746.png)
d. Kết quả mong đợi: Điều hướng tới trang đăng kí và cho phép thành viên đăng kí

**Comment by 31141021821** [comment]
Đây là lỗi phi chức năng. Nhóm cần xem lại
