### ISSUE TITLE
[Nhóm #8] Lỗi phi chức năng trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31141023653** [UEHMonQAQC/K40#3]
a. web browser: Cốc Cốc phiên bản 61.4.120.
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang http://online.ueh.edu.vn/.
ii. #2: Đăng nhập MSSV và mật khẩu.
iii. #3: click vào thông tin cá nhân
iV. #4: click chuột phải chọn kiểm tra như hình
![new bitmap image 2](https://cloud.githubusercontent.com/assets/26570677/25030813/f80201fe-20f1-11e7-8b8f-1d22a0907b83.png)

V: #5: Thay đổi thông tin ( ví dụ niên khóa lớp học)
![image](https://cloud.githubusercontent.com/assets/26570677/25030919/e8f4ddfc-20f2-11e7-8856-87e7268c4aa5.png)

c. Kết quả thực tế: Thông tin lớp học, khóa học bị thay đổi
![212323](https://cloud.githubusercontent.com/assets/26570677/25030879/88e19356-20f2-11e7-90d1-b197e8065016.png)
d. Kết quả mong muốn: Sinh viên không thể tự thay đổi nội dung thông tin khóa học theo ý mình.

**Comment by 31141022331** [comment]
Mình nhận bài này nhé.

**Comment by 31141022331** [comment]
Xin lỗi bạn nhóm bạn nhé, do mình không kiểm tra kĩ, khi mình F5 lại trang thì nội dung bạn thay đổi sẽ mất nhé nên đây không phải là lỗi.
