### ISSUE TITLE
[Nhóm #1] Lỗi phi chức năng trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31141021142** [UEHMonQAQC/K40#36]
a. Web Browser : Google Chrome  58.0.3029.96 (64-bit)
b. Các bước phát hiện lỗi: 
i. #1: Truy cập trang : http://online.ueh.edu.vn
ii. #2: Chọn Đăng nhập.
iii. #3: Điền tên đăng nhập và mật khẩu.
iv. #4: Vào trang Thông tin sinh viên
v. #5: Chọn 1 dòng thông tin, ở đây là Tôn giáo, chuột phải chọn Kiểm tra.
 
![image](https://cloud.githubusercontent.com/assets/26577319/25735863/8534382e-3198-11e7-855a-6292c11b287e.png)

vi. #6: Chuột phải chọn Edit as HTML.
 
![image](https://cloud.githubusercontent.com/assets/26577319/25735866/88ef6b96-3198-11e7-8ed2-1e6defc640fd.png)

vii. #7: Đánh vào thông tin, ở đây là ‘Chào nhé”, Nhấp vào điểm bất kì bên ngoài.
viii. #8: Thông tin nhập vào xuất hiện trong trang.
 
![image](https://cloud.githubusercontent.com/assets/26577319/25735871/8ced92b8-3198-11e7-9dda-f392245c02d2.png)

c. Kết quả thực tế: Xuất hiện thông tin không mong muốn, có thể sửa lại mà không cần thông qua nhà trường.
d. Kết quả mong đợi: sinh viên không thể tự sửa trong html được.

**Comment by 31131021217** [comment]
Xác nhận lỗi đúng như mô tả, cảm ơn các bạn.

**Comment by 31131021217** [comment]
Xin lỗi nhóm nhưng mình refresh trang thì thông tin vẫn trở về như cũ nên đây không phải lỗi. Các bạn tìm lỗi khác nha.
Cảm ơn các bạn.
