### ISSUE TITLE
[Nhóm #1] Lỗi chức năng trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31141021142** [UEHMonQAQC/K40#40]
a. Web Browser : Google Chrome  58.0.3029.96 (64-bit)
b. Các bước phát hiện lỗi: 
i. #1: Truy cập trang : http://online.ueh.edu.vn/
ii. #2: Chọn mục Tuyển sinh
![loi7](https://cloud.githubusercontent.com/assets/26577319/25738851/7a3f500a-31a9-11e7-9b74-b0a3066d7446.png)

iii. #3: Trong trang Tuyển sinh, chọn mục Tra cứu điểm tuyển sinh
iv. #4: Điền năm tra cứu và tên thí sinh vào, ở đây là “Hưng”.
![loi8](https://cloud.githubusercontent.com/assets/26577319/25738858/7daed6d4-31a9-11e7-8461-0c68b205f5a9.png)

c. Kết quả thực tế: Trang lỗi.
![image](https://cloud.githubusercontent.com/assets/26577319/25738868/893c6fd4-31a9-11e7-8770-d76b67347b64.png)

d. Kết quả mong đợi: Tra cứu được điểm tuyển sinh của thí sinh và năm tuyển sinh đã điền vào.

**Comment by 31131021217** [comment]
Lỗi này đã được phát hiện vào năm trước bởi K39: https://github.com/MonQAQCTH39/MonQAQCTH39/issues/10 
Các bạn vui lòng tìm lỗi khác nha. Cảm ơn các bạn.
