### ISSUE TITLE
[Nhóm #3] Lỗi font hiển thị trên trang http://thkt.ueh.edu.vn

### ISSUE THREAD

**Issue by 31141021498** [UEHMonQAQC/K40#51]
a. Web Browser:  Google Chrome Version 57.0.2987.133 (64-bit)
 b.  Các bước phát hiện lỗi:
   i.  #1: Truy cập trang http://thkt.ueh.edu.vn
   ii.  #2: Vào mục giới thiệu và contact
![thkt_1](https://cloud.githubusercontent.com/assets/26567144/25773763/afe5a51a-32ad-11e7-87b4-c57d002d92b5.PNG)
![thkt_2](https://cloud.githubusercontent.com/assets/26567144/25773764/b56bce10-32ad-11e7-9ebf-76e2cc3f7963.PNG)

 c. Kết quả thực tế: Size Font chữ không đồng nhất đối với các tiêu đề và văn bản.
 d.  Kết quả mong đợi: Sử dụng kích thước font chữ đồng nhất, đồng đều.

**Comment by 31141021821** [comment]
cái này là do ý tưởng thiết kế và trình bày của người viết trang, chứ không phải lỗi giao diện nha.
