### ISSUE TITLE
[NHÓM #5] Lỗi giao diện trên trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by NhaPhuong59** [UEHMonQAQC/K40#60]
a. web browser: cốc cốc-phiên bản 63.4.150
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://daotao.ueh.edu.vn/
ii. #2: Thấy hiện trên màn hình ở mục đăng ký học phần thiếu khoảng cách giữa dấu ")" và chữ "theo" 
c. Kết quả thực tế: thiếu khoảng trắng
`<img [src=](http://imgur.com/S3IYjoF)>
![image](https://cloud.githubusercontent.com/assets/26613518/25833576/82af7e7c-349c-11e7-861e-650ded377803.png)

d. Kết quả mong đợi: ở mục đăng ký học phần có khoảng cách giữa dấu ")" và chữ "theo"

**Comment by 31141020715** [comment]
Tất nhiên các bạn có thể xem lỗi chính tả cũng là một loại lỗi giao diện, nhưng lỗi này quá nhỏ để bị xem là lỗi. Nếu xét những chi tiết nhỏ như thế này thì có lẽ phải có cả triệu lỗi tương tự trên hệ thống site UEH.
