### ISSUE TITLE
[Nhóm#5] Lỗi giao diện trên trang http://daotao.ueh.edu.vn 

### ISSUE THREAD

**Issue by NhaPhuong59** [UEHMonQAQC/K40#61]
a. Web Browser: Chrome- phiên bản 57.0.2987.133 
b. Các bước để phát hiện lỗi:
i. #1: truy cập trang http://daotao.ueh.edu.vn/tin-tuc/tin-trong-nam/dang-ky-hoc-phan/2016-5-4-thong-bao-dang-ky-hoc-phan---hoc-ky-cuoi---nam-2016 
ii. #2: thấy trên màn hình bảng thông tin thời gian đóng học phí không được hiển thị đầy đủ. 
c. Kết quả thực tế 
![image](https://cloud.githubusercontent.com/assets/26613518/25832948/216cd83e-3498-11e7-8c31-6237a2a15b3f.png)

d. Kết quả mong đợi: hiển thị đầy đủ bảng thông tin nội dung.

**Comment by 31141020715** [comment]
Ở ngay dưới bảng thông tin này có một thanh cuộn ngang, có thể cuộn trang sang bên phải để xem toàn bộ nội dung của bảng thông tin.
