### ISSUE TITLE
[Nhóm#5] lỗi giao diện ở trang http://llct.ueh.edu.vn/

### ISSUE THREAD

**Issue by NhaPhuong59** [UEHMonQAQC/K40#64]
a. Web Browser: cốc cốc-Phiên bản 63.4.150
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://llct.ueh.edu.vn/
ii. #2: Thấy hiện trên màn hình khi click chuột vào số 1 và 2 thì thấy mất vài chữ
c. Kết quả thực tế: mất một phần của chữ
![image](https://cloud.githubusercontent.com/assets/26613518/25833381/170cf3a8-349b-11e7-806b-b31292fda607.png)
![image](https://cloud.githubusercontent.com/assets/26613518/25833387/26fec8ea-349b-11e7-8563-472885c96a63.png)
d. Kết quả mong đợi: dòng chữ hiện rõ ràng, đầy đủ khi click vào 1 và 2

**Comment by 31141020715** [comment]
Lỗi này bị trùng với lỗi mà nhóm 6 đã phát hiện trước đó. Theo nguyên tắc thì sẽ chỉ công nhận cho nhóm nào phát hiện trước.
