### ISSUE TITLE
[Nhóm#5] lỗi chức năng ở trang http://tthtsv.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by NhaPhuong59** [UEHMonQAQC/K40#65]
a.	Web browser: Chrome 57.0.2987.133
b.	Các bước để phát hiện lỗi:
#1: Truy cập vào trang  tthtsv.ueh.edu.vn
#2: Chọn mục Giới thiệu
#3: Góc phải trong đề mục Liên kết web, nhấp vào đường dẫn link UEH Café
c.	Kết quả thực tế: không hiển thị website của UEH Cafe
[http://tthtsv.ueh.edu.vn/trung-tam-ho-tro-sinh-vien#](url)
![image](https://cloud.githubusercontent.com/assets/26613518/25833635/fe0be588-349c-11e7-99da-9d15e95ddeff.png)
d.	Kết quả mong đợi: hiển thị website của UEH Cafe ở tab hiện tại hoặc tab mới

**Comment by 31141020048** [comment]
Sau khi nhóm QA kiểm tra lại thì lỗi của nhóm bạn trùng với nhóm 8.. Nên mình lấy lỗi của nhóm nộp trước, do đó lỗi này của nhóm bạn sẽ không được tính nữa vì nhóm 8 nộp trước.
Mong nhóm bạn thông cảm.
