### ISSUE TITLE
[Nhóm #7] – Lỗi chức năng – Chức năng “gửi phản hồi” không hoạt động - ở trang http://www.lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31141022783** [UEHMonQAQC/K40#69]
a. Web Browser: Phiên bản 58.0.3029.96 (64-bit)
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang  http://www.lib.ueh.edu.vn/Default.aspx?ArticleId=081e0c3e-7437-47fc-bfd9-7dd30f3ad071
ii. #2: Click vào button “gửi phản hồi”
![ch c nang 2](https://cloud.githubusercontent.com/assets/26600322/25834170/57d283bc-34a0-11e7-8ec2-e72f56ff7a89.PNG)
c. Kết quả thực tế: Trang web không trả về kết quả gửi phản hồi như mong đợi mà giữ nguyên trạng thái như ban đầu.
d. Kết quả mong đợi: Trả về kết quả một bảng form phản hồi và có thể submit.

**Comment by 31141022331** [comment]
Lỗi này đã bị trùng với nhóm 8, bạn tìm lỗi khác nhé.
