### ISSUE TITLE
[Nhóm #7] – Lỗi giao diện – Bố cục bài viết không đồng đều - ở trang http://tckt.ueh.edu.vn

### ISSUE THREAD

**Issue by 31141022783** [UEHMonQAQC/K40#71]
a. Web Browser: Phiên bản 58.0.3029.96 (64-bit)
b. Các bước phát hiện lỗi
i. #1 Truy cập trang: http://tckt.ueh.edu.vn/ToChuc/?NO_OBJ=155418
ii. #2 Trên trang hình ảnh load được có kích thước không đồng bộ với bố cục bài viết.
![giao di n 2](https://cloud.githubusercontent.com/assets/26600322/25834517/a83861d0-34a2-11e7-8e15-77c3f59a0c1c.PNG)
c. Kết quả thực tế: Hình load kích thước quá lớn, không đồng đều
d. Kết quả mong đợi: Hình ảnh load được có kích thước nhỏ hơn phù hợp với bố cục bài viết.

**Comment by 31141022331** [comment]
Mình nhận bài này nhé.

**Comment by 31141020048** [comment]
Sau khi nhóm QA kiểm tra lại thì lỗi của nhóm bạn trùng với nhóm 1. Nên mình lấy lỗi của nhóm nộp trước, do đó lỗi này của nhóm bạn sẽ không được tính nữa vì nhóm 1 nộp trước.
Mong nhóm bạn thông cảm.
